### PR TITLE
[*] MO: new hook 'displaySocialSharing' and use it

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR.

Best regards.

**Comment by jeromenadaud** [comment]
Hi @PrestaEdit can you please make upgrade file with this new hook in order to be available in already installed shop?

Best regards

**Comment by PrestaEdit** [comment]
Hi @jeromenadaud ; just do it here: https://github.com/PrestaShop/socialsharing/pull/19

**Comment by jeromenadaud** [comment]
Merged! Thanks

**Comment by PrestaEdit** [comment]
:+1: With pleasure.

**Pull request merged**
