### PR TITLE
[-] MO : Fix Fatal error: Call to undefined method CompareController:…

### PR DESCRIPTION
**Pull request by gRoussac**
…:getProduct()

### CODE REVIEW

**Comment by gRoussac** [comment]
:shipit:

**Comment by jeromenadaud** [comment]
Hey @gRoussac what do you think about this one : #20 ?

**Comment by gRoussac** [comment]
Hi,

I beleiev it is wrong. The module needs to be displayed on both pages, error excepted.

Regards

**Comment by gRoussac** [comment]
@maximebiloe  :fire:

**Comment by gRoussac** [comment]
Hi @jeromenadaud, please make a new version of the module. 

Best regards

**Comment by gRoussac** [comment]
:up please

**Pull request merged**
